In [2]:
import torch
print(torch.__version__)

2.10.0


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available.Using CPU.")

GPU is not available.Using CPU.


In [6]:
a=torch.empty(2,3)

In [7]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.7509, 0.1165, 0.6137],
        [0.1659, 0.5298, 0.1271]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
print("using arange->",torch.arange(0,10))

using arange-> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
print("using eye->",torch.eye(5))

using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [18]:
print("using full->",torch.full((3,3),5))

using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [19]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
x.dtype

torch.int64