In [22]:
import torch
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(

            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid(),

        )
    def forward(self,features):
        out=self.network(features)
        return out


In [23]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.5319],
        [0.5369],
        [0.5369],
        [0.5369],
        [0.5369],
        [0.5369],
        [0.5369],
        [0.5369],
        [0.5402],
        [0.5369]], grad_fn=<SigmoidBackward0>)

In [19]:
model.linear1.bias

Parameter containing:
tensor([ 0.0609, -0.0788, -0.2188], requires_grad=True)

In [20]:
model.linear2.weight

Parameter containing:
tensor([[-0.5665,  0.4686,  0.2556]], requires_grad=True)

In [25]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00