In [40]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [41]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/breast-cancer-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/kpvarma/.cache/kagglehub/datasets/yasserh/breast-cancer-dataset/versions/1


In [42]:
df=pd.read_csv('breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [43]:
df.shape

(569, 32)

In [44]:
df.drop(columns=['id'],inplace=True)

In [45]:
df.shape

(569, 31)

In [46]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [47]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [48]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [49]:
X_train.shape

(455, 30)

In [50]:
y_test.shape

(114,)

In [51]:
y_train.shape

(455,)

In [52]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [53]:
y_train

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,

In [54]:
y_train.shape

(455,)

In [55]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [56]:
X_train_tensor.shape

torch.Size([455, 30])

In [57]:
X_test_tensor.shape

torch.Size([114, 30])

In [58]:
import torch

class MySimpleNN():

    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

In [59]:
learning_rate=0.1
epochs=25


In [60]:
model=MySimpleNN(X_train_tensor)
model.weights

tensor([[0.2479],
        [0.8405],
        [0.7976],
        [0.6115],
        [0.7608],
        [0.4163],
        [0.3748],
        [0.2774],
        [0.1496],
        [0.1696],
        [0.2790],
        [0.8097],
        [0.5443],
        [0.9167],
        [0.4214],
        [0.3119],
        [0.1566],
        [0.4601],
        [0.7671],
        [0.2749],
        [0.9539],
        [0.5120],
        [0.3347],
        [0.7606],
        [0.2242],
        [0.3260],
        [0.5617],
        [0.7883],
        [0.5549],
        [0.9012]], dtype=torch.float64, requires_grad=True)

In [61]:
model.bias


tensor([0.], dtype=torch.float64, requires_grad=True)

In [62]:
epochs = 100
learning_rate = 0.01

model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):

    # Forward
    y_pred = model.forward(X_train_tensor)

    # Loss
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward
    loss.backward()

    # Update weights
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.38999945859215
Epoch: 2, Loss: 3.3763971413291363
Epoch: 3, Loss: 3.3625635426883016
Epoch: 4, Loss: 3.3486173444986975
Epoch: 5, Loss: 3.3346812440164877
Epoch: 6, Loss: 3.3207554321970405
Epoch: 7, Loss: 3.306840104247729
Epoch: 8, Loss: 3.2929354596867495
Epoch: 9, Loss: 3.279041702451248
Epoch: 10, Loss: 3.26515904092747
Epoch: 11, Loss: 3.2512876880783153
Epoch: 12, Loss: 3.2374278614754624
Epoch: 13, Loss: 3.223579783399114
Epoch: 14, Loss: 3.209743680903008
Epoch: 15, Loss: 3.1959197858695427
Epoch: 16, Loss: 3.182108335100564
Epoch: 17, Loss: 3.168309570355733
Epoch: 18, Loss: 3.154523738437505
Epoch: 19, Loss: 3.140751091236869
Epoch: 20, Loss: 3.1269918857856753
Epoch: 21, Loss: 3.113246384325965
Epoch: 22, Loss: 3.0995148543362614
Epoch: 23, Loss: 3.0857975685970715
Epoch: 24, Loss: 3.071975625974619
Epoch: 25, Loss: 3.057815844457008
Epoch: 26, Loss: 3.043671642632864
Epoch: 27, Loss: 3.0293474177977036
Epoch: 28, Loss: 3.014727931363121
Epoch: 29, Loss: 3

In [63]:
model.bias


tensor([-0.0210], dtype=torch.float64, requires_grad=True)

In [64]:
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.9).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f"Accuracy:{accuracy.item()}")

Accuracy:0.5400123000144958
